### ISSUE TITLE
[Question] Any chance for a 1.18.2 update?

### ISSUE THREAD

**Issue by oliviathevampire** [FreeSoccerHDX/AdvancedWorldCreatorAPI#1]
Hi! I found this randomly and thought it seemed pretty cool! I was just wondering if you have any chance of making a version of this for 1.18.2? I know it broke a lot of mods and probably a lot of plugins.

**Comment by Dev0Louis** [comment]
[Update to 1.18.2 (Beta)](https://www.spigotmc.org/resources/advancedworldcreatorapi.89100/update?update=449603)
