### ISSUE TITLE
[Question] Repository and Dependency

### ISSUE THREAD

**Issue by JoloJanssen** [FreeSoccerHDX/AdvancedWorldCreatorAPI#2]
I would like to use this API in my plugin.
Where can I find the repository and dependency (for maven) that I need?

**Comment by FreeSoccerHDX** [comment]
Hey,
this Project is not available somewhere.
You need to pull the project and run: maven install 
After that you can use it as dependency as uasual.

**Comment by JoloJanssen** [comment]
> You need to pull the project and run: maven install

Won't that shade the API into my plugin? I'm sorry, i'm kinda new to dependencies and API use
Your API looks very cool tho, so i'd love to use it.

**Comment by FreeSoccerHDX** [comment]
Depends on what you do....
if you download and use maven install you cann use this:
`        <dependency>
            <groupId>de.freesoccerhdx</groupId>
            <artifactId>advancedworldcreatorapi</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
`
The Server just needs the Jar (can be downloaded at spigot) and it should work

**Comment by JoloJanssen** [comment]
I am fine with it being provided in the plugins folder, thank you for the dependecy.
But if I add this dependecy and update with Maven I get this error:

Could not find artifact de.freesoccerhdx:advancedworldcreatorapi:pom:1.0-SNAPSHOT in spigotmc-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/)

**Comment by FreeSoccerHDX** [comment]
Did you pull and run maven install ?

**Comment by JoloJanssen** [comment]
How do you pull? I found some sources online, but InteliJ (what I use) just updated its interface, so I cant follow them along

**Comment by FreeSoccerHDX** [comment]
use somwhere:
"git clone https://github.com/FreeSoccerHDX/AdvancedWorldCreatorAPI.git"
go into the version you want and run maven install

**Comment by FreeSoccerHDX** [comment]
Another option is to add the jar directly to the project, that sould work a lot easieer but for that you need google.

**Comment by JoloJanssen** [comment]
> use somwhere:

what do you mean with somewhere. Am I looking for something specific?

**Comment by FreeSoccerHDX** [comment]
Just go for this way:
https://stackoverflow.com/questions/1051640/correct-way-to-add-external-jars-lib-jar-to-an-intellij-idea-project

**Comment by JoloJanssen** [comment]
Thank you.
I will have to manually add it everytime I update Maven don't I?

**Comment by FreeSoccerHDX** [comment]
I dont think so

**Comment by JoloJanssen** [comment]
completely different question, but this error is caused by the API being for 1.20 and my plugin being for 1.20.2?
![image](https://github.com/FreeSoccerHDX/AdvancedWorldCreatorAPI/assets/74826171/3b9947e8-79d9-4925-ac4d-d855d5c9b4da)

**Comment by FreeSoccerHDX** [comment]
I think its not compatible ... give me some time then can i look through it
